---
# Vars:
# - : ""

PreTasks:
- name: "Restart runtime"
  command: "./nu_scripts/start_rt.sh"

PostTasks:
- name: "Shutdown runtime"
  command: "./nu_scripts/stop_rt.sh"

PrerunGdbCommands:
- name: "enable async mode"
  command: "set target-async on"
- name: "enable non-stop mode"
  command: "set non-stop on"

Components:
# TODO: Supports for pid (latter attach), remote attach 
- mode: local 
  tag: proclet_server_0
  bin: "./nu_bin/test_migrate"
  args: [ "-l", "1", "-i", "18.18.1.2" ]
- mode: local
  tag: proclet_server_1
  bin: "./nu_bin/test_migrate"
  args: [ "-l", "1", "-i", "18.18.1.3" ]
- mode: local
  tag: proclet_server_entry
  bin: "./nu_bin/test_migrate"
  args: [ "-l", "1", "-i", "18.18.1.4", "-m"]
  run_delay: 10
