---
# PreTasks:
# - name: "Restart runtime"
#   command: "./nu_scripts/start_rt.sh"

# PostTasks:
# - name: "Shutdown runtime"
#   command: "./nu_scripts/stop_rt.sh"

Components:
- addr: localhost:9898
  mode: remote 
  tag: test_server_1 
  cwd: "/proj/flashburst-PG0/code/distributed-debugger"
  bin: "./bin/multithread_print"
  args: []
- addr: localhost:9999
  mode: remote
  tag: test_server_2
  cwd: "/proj/flashburst-PG0/code/distributed-debugger"
  bin: "./bin/multithread_print"
  args: []

