---
Components:
# TODO: Supports for pid (latter attach), remote attach 
- addr: localhost
  tag: proclet_server_0
  bin: "./nu_bin/test_migrate"
  args: [ "-l", "1", "-i", "18.18.1.2" ]
- addr: localhost
  tag: proclet_server_1
  bin: "./nu_bin/test_migrate"
  args: [ "-l", "1", "-i", "18.18.1.3" ]
- addr: localhost
  tag: proclet_server_entry
  bin: "./nu_bin/test_migrate"
  args: [ "-l", "1", "-i", "18.18.1.4", "-m"]
  run_delay: 3
