#!/bin/bash
#
# free_disk_cloudlab.sh — Reclaim root-filesystem space on a CloudLab node.
#
# The images used by these experiments have a 16 GB root filesystem, and the
# tooling the harnesses pull in (docker images, go module/build caches, apt
# archives, systemd journal) all lands there by default. A full / breaks k3s,
# docker builds, and anything that writes to /tmp. This script removes ONLY
# pure caches -- data that is either regenerated automatically or re-downloaded
# on demand -- so it is always safe to run, on the head node or any worker.
#
# What it cleans (everything below is a cache):
#   * apt package archives        (/var/cache/apt)      -- re-downloaded by apt
#   * systemd journal, keep 50M   (/var/log/journal)    -- old logs only
#   * Go build cache              (~/.cache/go-build)   -- regenerated by builds
#   * Go module cache             (~/go/pkg/mod)        -- re-downloaded by builds
#   * pip download cache          (~/.cache/pip)        -- re-downloaded by pip
#   * docker build cache + dangling images              -- regenerated by builds
#
# What it deliberately does NOT touch:
#   * tagged docker images (golang:*, the app image)    -- avoids an 800 MB re-pull
#   * ~/.rustup, ~/.cargo                               -- needed to rebuild ddb
#   * /usr/src/linux-*                                  -- running kernel's source;
#                                                          Nu's ksched builds against it
#   * /var/lib/rancher, /var/lib/docker                 -- live k3s / docker state
#   * anything under the repo, /mnt/local, ~/ddb-tmp,
#     experiment logs/ or results/                      -- your code and your data
#
# Usage:  ./free_disk_cloudlab.sh
#         (per worker: ssh <node> 'bash -s' < free_disk_cloudlab.sh)

set -uo pipefail

echo "=== Root filesystem before ==="
df -h / | sed 's/^/  /'
avail_before=$(df --output=avail -k / | tail -1)

step() { printf '\n--- %s\n' "$1"; }

# ─── apt package archives ────────────────────────────────────────────────────
step "apt package cache"
if command -v apt-get >/dev/null 2>&1; then
  before=$(sudo du -sk /var/cache/apt 2>/dev/null | cut -f1)
  sudo apt-get clean 2>/dev/null
  after=$(sudo du -sk /var/cache/apt 2>/dev/null | cut -f1)
  echo "  freed $(( (${before:-0} - ${after:-0}) / 1024 )) MB"
else
  echo "  apt not present, skipped"
fi

# ─── systemd journal (keep the most recent 50M) ──────────────────────────────
step "systemd journal (keeping 50M)"
if command -v journalctl >/dev/null 2>&1; then
  # --rotate archives the active files so --vacuum-size may remove them; fully
  # active files cannot (and should not) be removed, so some residue is normal.
  sudo journalctl --flush --rotate 2>/dev/null
  sudo journalctl --vacuum-size=50M 2>&1 | tail -1 | sed 's/^/  /'
else
  echo "  journalctl not present, skipped"
fi

# ─── Go caches ───────────────────────────────────────────────────────────────
step "Go build + module caches"
GO_BIN="$(command -v go || echo /usr/local/go/bin/go)"
if [[ -x "$GO_BIN" ]]; then
  # go clean also handles the module cache's read-only permission bits.
  "$GO_BIN" clean -cache    2>/dev/null && echo "  build cache cleared"
  "$GO_BIN" clean -modcache 2>/dev/null && echo "  module cache cleared (re-downloaded on next build)"
else
  # No toolchain: the build cache is still plain user-owned files.
  rm -rf "$HOME/.cache/go-build" 2>/dev/null && echo "  build cache cleared"
  echo "  go toolchain not present; module cache left alone"
fi

# ─── pip download cache ──────────────────────────────────────────────────────
step "pip cache"
pip3 cache purge >/dev/null 2>&1 && echo "  purged" || echo "  nothing to purge / pip not present"

# ─── docker: build cache + dangling (untagged) images only ───────────────────
step "docker build cache + dangling images"
if docker info >/dev/null 2>&1; then
  docker builder prune -f 2>&1 | tail -1 | sed 's/^/  /'
  docker image prune  -f 2>&1 | tail -1 | sed 's/^/  /'
  echo "  (tagged images kept -- 'docker rmi golang:1.21.1' frees ~800 MB more"
  echo "   if you accept a re-pull on the next ./build_app.sh)"
else
  echo "  docker not usable (not installed, or run 'newgrp docker'), skipped"
fi

# ─── Summary ─────────────────────────────────────────────────────────────────
echo ""
echo "=== Root filesystem after ==="
df -h / | sed 's/^/  /'
avail_after=$(df --output=avail -k / | tail -1)
echo ""
echo "Reclaimed $(( (avail_after - avail_before) / 1024 )) MB."
