---
# PreTasks:
# - name: "Restart runtime"
#   command: "./nu_scripts/start_rt.sh"

# PostTasks:
# - name: "Shutdown runtime"
#   command: "./nu_scripts/stop_rt.sh"

Components:
- addr: localhost
  tag: test_server_1 
  bin: "./bin/multithread_print"
  cwd: "/home/ubuntu/USC-NSL/distributed-debugger"
  args: []
