---
Framework: grpc

PrerunGdbCommands:
- name: "pass SIGINT to program"
  command: "handle SIGINT nostop pass"

ServiceDiscovery:
  Broker:
    hostname: 127.0.0.1
    managed:
      type: emqx

Conf:
  on_exit: kill
  auto_shutdown: false
