---
# PreTasks:
# - name: "Restart runtime"
#   command: "./nu_scripts/start_rt.sh"

# PostTasks:
# - name: "Shutdown runtime"
#   command: "./nu_scripts/stop_rt.sh"
# Framework: serviceweaverkube

Framework: nu

# PrerunGdbCommands:
# - name: "enable script"
#   command: "source ../gdb_ext/runtime-gdb-grpc.py"
# - name: "enable non-stop mode"
#   command: "set non-stop off"

# SSH:
#   user: ybyan
  # port: 22

ServiceDiscovery:
  Broker:
    hostname: 127.0.0.1
    managed:
      type: emqx

Conf:
  on_exit: kill
  sudo: true
  support_migration: true 
  gdb:
    logging: false
