---
Framework: Nu

# PreTasks:
# - name: "configure gdb"
#   command: "echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope"

# PostTasks:
# - name: "Shutdown runtime"
#   command: "./nu_scripts/stop_rt.sh"

Conf:
  sudo: true

PrerunGdbCommands:
- name: "disable CALADAN's custom signal handling"
  command: "handle SIGUSR1 SIGUSR2 nostop noprint"


PostrunGdbCommands:
- name: "auto continue attached process"
  command: "-exec-continue"

#   user: ybyan
  # port: 22

ServiceDiscovery:
  Broker:
    hostname: 10.10.2.12
