---
# PreTasks:
# - name: "Restart runtime"
#   command: "./nu_scripts/start_rt.sh"

# PostTasks:
# - name: "Shutdown runtime"
#   command: "./nu_scripts/stop_rt.sh"
Framework: Nu
Components:
- addr: localhost
  tag: test_server_1 
  bin: "./bin/nested_frame"
  args: []
