Framework: serviceweaver_kube
PrerunGdbCommands:
- name: "load extension"
  command: "source /usr/src/app/gdb_ext/noobextension.py"

Components:
  kube_namespace: default
  binary_name: "serviceweaver1"